### ISSUE TITLE
Add prettier

### ISSUE THREAD

**Issue by IanVS** [sem-js/sem-js#9]

**Comment by chriscain** [comment]
Hey sem-js! I'm gonna snag this one.

**Comment by chriscain** [comment]
Looks like this is already done! I'll try a different one 😄

**Comment by wommy** [comment]
are we just leaving the gatsby default?
- https://github.com/sem-js/sem-js/blob/master/.prettierrc
- https://github.com/sem-js/sem-js/blob/master/.prettierignore

**Comment by IanVS** [comment]
@wommy yeah I think the defaults are fine for now, unless you have specific suggestions you think we'd want to change.
